version: '3'
services:
  crawl-app:
    build: .
    image: localhost:3001/thainv1612/crawl-app
    container_name: crawl-app
    working_dir: /var/www/
    ports:
      - "3001:3001"
    volumes:
      - .:/var/www/
    networks:
      - crawl-network
networks:
  crawl-network:
    driver: bridge
